services:
  # dein Webservice
  - type: web
    name: profiausbau-chatbot-backend
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORG_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REST_URL
        sync: false
      - key: UPSTASH_REST_TOKEN
        sync: false

  # Cron Job für den Scraper
  - type: cron
    name: profiausbau-scraper
    env: node
    plan: free
    schedule: "0 3 * * *"   # jeden Tag um 03:00 Uhr UTC
    buildCommand: "npm install"
    startCommand: >
      LLMS_SOURCES="https://www.profiausbau.com/llms.txt,https://www.profiausbau.com/llms-full.txt"
      BACKEND_URL="https://profiausbau-chatbot-backend.onrender.com/api/faq"
      node tools/scrape_llms_to_faq.mjs
